import {
  IsArray,
  IsBoolean,
  IsNumber,
  IsObject,
  IsOptional,
  IsString,
} from 'class-validator';
import { ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import { CommonTypeDto } from './common-type.dto';
import { ContractTypeDto } from './contract-type.dto';

export class GetTemplatesResponseDto {
  @ApiPropertyOptional()
  @IsOptional()
  @IsNumber()
  id: number;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  name: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsNumber()
  executorId: number | null;

  @ApiPropertyOptional()
  @IsOptional()
  @IsNumber()
  customerId: number | null;

  @ApiPropertyOptional()
  @IsOptional()
  @IsNumber()
  executorLegalTypeId: number | null;

  @ApiPropertyOptional()
  @IsOptional()
  @IsNumber()
  executorLangId: number | null;

  @ApiPropertyOptional()
  @IsOptional()
  @IsNumber()
  customerLegalTypeId: number | null;

  @ApiPropertyOptional()
  @IsOptional()
  @IsNumber()
  customerLangId: number | null;

  @ApiPropertyOptional()
  @IsOptional()
  @IsNumber()
  contractTypeId: number | null;

  @ApiPropertyOptional()
  @IsOptional()
  @IsNumber()
  docTypeId: number | null;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  fileName: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  filePath: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsBoolean()
  isDefault: boolean;

  @ApiPropertyOptional()
  @IsOptional()
  @IsBoolean()
  isAutoGenerated: boolean;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  group: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  created_at: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  updated_at: string;

  @ApiPropertyOptional({ type: CommonTypeDto })
  @IsOptional()
  @Type(() => CommonTypeDto)
  @IsObject()
  executorLang: CommonTypeDto;

  @ApiPropertyOptional({ type: CommonTypeDto })
  @IsOptional()
  @Type(() => CommonTypeDto)
  @IsObject()
  executorLegalType: CommonTypeDto;

  @ApiPropertyOptional({ type: CommonTypeDto })
  @IsOptional()
  @Type(() => CommonTypeDto)
  @IsObject()
  customerLang;

  @ApiPropertyOptional({ type: CommonTypeDto })
  @IsOptional()
  @Type(() => CommonTypeDto)
  @IsObject()
  customerLegalType: CommonTypeDto;

  @ApiPropertyOptional({ type: CommonTypeDto })
  @IsOptional()
  @Type(() => CommonTypeDto)
  @IsObject()
  DocType: CommonTypeDto;

  @ApiPropertyOptional({ type: ContractTypeDto })
  @IsOptional()
  @Type(() => ContractTypeDto)
  @IsObject()
  ContractType: ContractTypeDto;

  @ApiPropertyOptional()
  @IsOptional()
  @IsArray()
  partners: number[];
}
