version: '3.9'
services:
  user:
    container_name: user
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    env_file:
      - .env.development
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn start:dev
    ports:
      - "50053:50053"
